# Copyright 2025 Atakku <https://atakku.dev>
#
# This project is dual licensed under MIT and Apache.

# Gradle setup
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true

# Mod properties
mod_id=fsmp_bridge
mod_name=fsmp-bridge
mod_group=dev.atakku.fsmp
mod_version=2.1.2

minecraft_version=1.21.1
mappings_version=2024.11.17
neo_version=21.1.209

# Dependencies
fabric_version=0.121.0+1.21.5
lombok_version=1.18.32
jda_version=5.2.2
dw_version=0.8.4
